### PR TITLE
Use huggingface hub for model distribution

### PR DESCRIPTION
**Pull request by Flova**
The model is now available of the Huggingface Hub: https://huggingface.co/Flova/omr_transformer
This allows us to distribute the model for free and share it with other people (it even features an automated web UI and API).

### CODE REVIEW

**Comment by Flova** [comment]
Afaik this happens with the current implementation. It looks in the local huggingface cache if the version of the model is present and pulls a new one if needed.

**Comment by Flova** [comment]
But I could be wrong.

**Comment by Flova** [comment]
Or am I missing something.

**Comment by Flova** [comment]
See https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.from_pretrained.pretrained_model_name_or_path

**Review by Juphex — APPROVED** [review]

**Pull request merged**
