### PR TITLE
Lilypond motion input

### PR DESCRIPTION
**Pull request by Flova**
Adds a lilypond parser that generates hit points with time annotations based on a lilypond string.

This PR is based on #26 and waits for it.

### CODE REVIEW

**Comment by Flova** [comment]
To test this run

```
roslaunch marimbabot_sim marimba_display.launch
```

Open another terminal and run

```
rosrun marimbabot_planning lilypond_to_hitpoint
```

Add the `/hit_marker` topic to rviz and run the last command again. You should see an arrow pointing at the different notes at the correct times.

**Comment by Flova** [comment]
https://user-images.githubusercontent.com/15075613/225627136-1c11fd93-4181-4cc0-b85d-0870d3351505.mp4

Demo

**Comment by Flova** [comment]
Note: This is not integrated with the vision or the motion planning yet. It just parses a hardcoded string and publishes a marker.

**Comment by berkgungor** [comment]
The green indicator in video does not follow the pattern which is in right corner(the notes that are hard coded) e.g. it does to C4, E6 and etc. What is the  story behind of this ?

**Comment by Flova** [comment]
The lilypond format denotes C4 as C
`c` and C5 as `c'` this is also what the vision predicts. The numbers are the durations e.g. `c'4` is a quarter note. The is also the format predicted by the vision. See examples on https://huggingface.co/Flova/omr_transformer

**Pull request merged**
